---
title: "DA2-Assignment-1"
author: "Gyongyver Kamenar (2103380)"
date: "11/20/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE)
```

```{r Libraries, include=FALSE}

# Loading packages 
if (!require("pacman")) {
  install.packages("pacman")
}
library(pacman)
pacman::p_load(tidyverse, ggplot2, modelsummary,
               kableExtra, stargazer, knitr, fixest, corrplot)
```

```{r Data, include=FALSE}

dt<-read.csv('morg-2014-emp.csv', header=TRUE)

summary(dt)

#  Variables
#  X |
# hhid| Household id
# intmonth| Interview month
# stfips| State codes
# weight| Final Weight x 100
# earnwke| weakly earnings
# uhours| usual working hours per week
# grade92| highest educational grade completed (31-46)
# race| race
# ethnic| ethnic
# age| age
# sex| sex male=1 female=2
# marital| 
  #marital status Married civilian spouse present 1
  # Married AF spouse present 2 
  # Married spouse absent or separated 3
  # Widowed or divorced(Through 88) 4
  # Widowed (After 88) 4
  # Divorced “ 5
  # Separated “ 6
  # Never Married 7

# ownchild| Number of own children
# chldpres| Presence of own children less than 18 in primary family
  #  Recodes of presence of own child variable. "1" indicates presence of one or more children in that age range, "0" indicates absence of children in the age ranges 0-2, 0-5, 3-5, 6-13, and 14-17 respectively. 

# prcitshp| Citizenship status
# state| Census Code for state
# ind02| Industry Classification Code
# occ2012| occupational code (census 2010 classification)
# class| class of worker
# unionmme| is...a member of a labor union or an employee association similar to a union?
# unioncov|  is...covered by a union or employee association contract?
# lfsr94| Employment Status Recode Last week.



```

```{r Data manipulation, include=FALSE}
# Filter datatable for the given occupations
data <- filter(dt, dt$occ2012 %in% c(1006,1007,1010,1020,1030) )


## Create hourly wage variable
  # earnwke is weekly earnings and uhours is usualy working hours per week
  # So is we want to compare people we have to create a better measure
  # earnhrs = earnwke/uhours
  # ln_earnhrs = log(earnwke/uhours)

## Re-factor male and female : male:0 and female:1 
  # For easier interpretation

## Factorise categorical variables inticated by integers

data <- data %>% mutate(
  earnhrs = earnwke/uhours,
  ln_earnhrs = log(earnwke/uhours), 
  sex= sex - 1,
  grade92 = as.factor(grade92),
  race = as.factor(race),
  ethnic = as.factor(ethnic),
  marital = as.factor(marital),
  chldpres = as.factor(chldpres),
  occ2012 = as.factor(occ2012)
)

#
data

```

### Introduction

The chosen occupations:

1006 Computer systems analysts
1007 Information security analysts
1010 Computer programmers
1020 Software developers, applications and systems software
1030 Web developers

### Descriptive statistics

### Modelling

### Summary


### Appendix
### Descriptive statistics
```{r Descriptive Statistics, echo=FALSE}

#descriptive statistics table 
datasummary( earnwke+ earnhrs+ ln_earnhrs + weight +uhours +as.numeric(grade92)+ age + ownchild +as.numeric(chldpres) ~  N + Percent() + Mean +SD + Min + Max +Median + P25 +P75, data = data,
            output = 'latex',
            title = 'Descriptive Statistics',
            notes = '')  

```

### check

```{r Descriptives 2, echo=FALSE}
kable(data %>% group_by(sex) %>% count() )
kable(data %>% group_by(grade92) %>% count())
```

```{r Models, echo=FALSE, message=FALSE, warning=FALSE}

reg1<-feols(ln_earnhrs ~ sex, data = data, vcov = 'hetero')

reg2<-feols(ln_earnhrs ~ sex + age , data = data, vcov = 'hetero')


reg3<-feols(ln_earnhrs ~ sex + age + grade92 , data = data, vcov = 'hetero')


reg4<-feols(ln_earnhrs ~ sex + age + grade92 + sex*grade92 , data = data, vcov = 'hetero')


reg5<-feols(ln_earnhrs ~ sex + age +poly(age,2) + grade92 + ownchild, data = data, vcov = 'hetero')


regtable<-etable(reg1,reg2,reg3,reg4,reg5, tex = FALSE)
#regtable

kable(regtable, "latex") %>% column_spec(1:6,width = "6em") %>%  
  kable_styling(bootstrap_options = "bordered", full_width = FALSE) %>% 
   row_spec(row = 0,
  bold = TRUE) %>%
  column_spec(column = 1, width = "6em", bold = TRUE,
  border_left = TRUE) %>%
  column_spec(column = 6, width = "6em",
  border_right = TRUE) 

```
### Correlation matrix
```{r Plots, echo=FALSE}

## Correlation matrix
corr_table<-data[,c(8,11,12,14,25)]
corr_table$grade92<-as.numeric(corr_table$grade92)
c1<-cor(corr_table)
corrplot(c1,type = "upper", addCoef.col = 'black',tl.col = "black", tl.cex = 0.9 )


```
```{r My theme, message=FALSE, warning=FALSE, include=FALSE}

theme_gyongyver<-function(base_size=12){
  # Use the basic properties of theme_bw
  theme_light() %+replace% 
    
    # Change the items
    theme(
      # The grids on the background
      panel.grid.major  = element_line(color = "slategray2"),
      panel.grid.minor = element_line(color="grey90"),
      # The background color
      panel.background  = element_rect(fill = "grey95"),
      # the axis line
      axis.line         = element_line(color = "navyblue"),
      # Littel lines called ticks on the axis
      axis.ticks        = element_line(color = "navy"),
      # Numbers on the axis
      axis.text         = element_text(color = "navy"),
      # NEW ONES
      # rectangle element
      rect = element_rect(fill="grey10",colour = "white"),
      # axis title
      axis.title = element_text(colour="mediumblue"),
      # plot background
      plot.background = element_rect(fill="white"),
      # title
      plot.title = element_text(family = "", colour="midnightblue", size=14, hjust = 0.5, vjust=0.8),
      plot.subtitle = element_text(family = "", colour="midnightblue", size=12, hjust = 0.5),
      #caption
      plot.caption = element_text(size = 9, colour = "steelblue3", hjust = 1),
      #legend
      legend.background = element_rect(fill = "grey80", colour = "grey80"),
      legend.text = element_text(colour = "black"),
      panel.border = element_blank()
      
    )
  
}

```


```{r Plot 2, echo=FALSE, message=FALSE, warning=FALSE}

# Age and earnhrs per gender
dt_mean<- data %>%  group_by(sex, age) %>% summarise_at(vars(ln_earnhrs), list(name=mean))


ggplot(dt_mean)+
  geom_smooth(aes(x=age, y=name, color=as.factor(sex)), method = 'loess')+
  labs(
    title = "Average earning per hour conditional on age by sex",
    y= "Mean earning per hour",
    x= "Age",
    color="Sex",
    caption = "Gyongyver Kamenar",
    
  )+
  theme_gyongyver()


```

